2025-03-19 13:53:58,856 INFO    MainThread:4132 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-19 13:53:58,856 INFO    MainThread:4132 [wandb_setup.py:_flush():67] Configure stats pid to 4132
2025-03-19 13:53:58,856 INFO    MainThread:4132 [wandb_setup.py:_flush():67] Loading settings from C:\Users\alexi\.config\wandb\settings
2025-03-19 13:53:58,858 INFO    MainThread:4132 [wandb_setup.py:_flush():67] Loading settings from c:\users\alexi\onedrive\documents\documents\école\centria\ai\third_module\wandb\settings
2025-03-19 13:53:58,858 INFO    MainThread:4132 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-19 13:53:58,858 ERROR   MainThread:4132 [wandb_setup.py:_flush():69] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\alexi\anaconda3\Lib\site-packages\spyder_kernels\customize\code_runner.py", line 506, in _exec_code
    exec_encapsulate_locals(
  File "C:\Users\alexi\anaconda3\Lib\site-packages\spyder_kernels\customize\utils.py", line 209, in exec_encapsulate_locals
    exec_fun(compile(code_ast, filename, "exec"), globals, None)
  File "c:\users\alexi\onedrive\documents\documents\école\centria\ai\third_module\astralalgorithmists_assignement_3.2.py", line 131, in <module>
    if __name__ == '__main__':
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexi\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 1482, in init
    wandb._sentry.reraise(e)
  File "C:\Users\alexi\anaconda3\Lib\site-packages\wandb\analytics\sentry.py", line 156, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "C:\Users\alexi\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 1427, in init
    wi.maybe_login(init_settings)
  File "C:\Users\alexi\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 175, in maybe_login
    wandb_login._login(
  File "C:\Users\alexi\anaconda3\Lib\site-packages\wandb\sdk\wandb_login.py", line 305, in _login
    key, key_status = wlogin.prompt_api_key()
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexi\anaconda3\Lib\site-packages\wandb\sdk\wandb_login.py", line 234, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
2025-03-19 13:53:58,863 INFO    MainThread:4132 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\users\alexi\onedrive\documents\documents\école\centria\ai\third_module\wandb\run-20250319_135358-kdc9ps27\logs\debug.log
2025-03-19 13:53:58,863 INFO    MainThread:4132 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\users\alexi\onedrive\documents\documents\école\centria\ai\third_module\wandb\run-20250319_135358-kdc9ps27\logs\debug-internal.log
2025-03-19 13:53:58,863 INFO    MainThread:4132 [wandb_init.py:init():761] calling init triggers
2025-03-19 13:53:58,863 INFO    MainThread:4132 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-19 13:53:58,863 INFO    MainThread:4132 [wandb_init.py:init():784] starting backend
2025-03-19 13:53:58,865 INFO    MainThread:4132 [wandb_init.py:init():788] sending inform_init request
2025-03-19 13:53:59,024 INFO    MainThread:4132 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-19 13:53:59,025 INFO    MainThread:4132 [wandb_init.py:init():798] backend started and connected
2025-03-19 13:53:59,028 INFO    MainThread:4132 [wandb_init.py:init():891] updated telemetry
2025-03-19 13:53:59,035 INFO    MainThread:4132 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-19 13:54:02,110 INFO    MainThread:4132 [wandb_init.py:init():990] starting run threads in backend
2025-03-19 13:54:03,465 INFO    MainThread:4132 [wandb_run.py:_console_start():2375] atexit reg
2025-03-19 13:54:03,466 INFO    MainThread:4132 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-19 13:54:03,466 INFO    MainThread:4132 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-19 13:54:03,467 INFO    MainThread:4132 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-19 13:54:03,617 INFO    MainThread:4132 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-19 13:54:03,994 INFO    MainThread:4132 [wandb_watch.py:_watch():71] Watching
2025-03-19 14:09:56,971 INFO    MainThread:4132 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\users\alexi\onedrive\documents\documents\école\centria\ai\third_module\wandb\run-20250319_140956-w53i6nuv\logs\debug.log
2025-03-19 14:09:56,972 INFO    MainThread:4132 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\users\alexi\onedrive\documents\documents\école\centria\ai\third_module\wandb\run-20250319_140956-w53i6nuv\logs\debug-internal.log
2025-03-19 14:09:56,972 INFO    MainThread:4132 [wandb_init.py:init():761] calling init triggers
2025-03-19 14:09:56,973 INFO    MainThread:4132 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-19 14:09:56,975 INFO    MainThread:4132 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-19 14:09:57,141 INFO    MainThread:4132 [wandb_watch.py:_watch():71] Watching
2025-03-19 15:49:51,542 INFO    MainThread:4132 [wandb_run.py:_finish():2112] finishing run alexis-mialon-epita/mnist-cnn/kdc9ps27
2025-03-19 15:49:51,543 INFO    MainThread:4132 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 0
2025-03-19 15:49:51,544 INFO    MainThread:4132 [wandb_run.py:_restore():2322] restore
2025-03-19 15:49:51,544 INFO    MainThread:4132 [wandb_run.py:_restore():2328] restore done
2025-03-19 15:49:52,694 INFO    MainThread:4132 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-19 15:49:52,694 INFO    MainThread:4132 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-19 15:49:52,694 INFO    MainThread:4132 [wandb_run.py:_footer_sync_info():3917] logging synced files
